version: '3.9'

services:
  server:
    pid: "host"
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: tm_server
    ports:
      - "50051:50051"
    restart: unless-stopped

  gateway:
    build:
      context: ./gateway
    container_name: tm_gateway
    ports:
      - "3001:3001"
    environment:
      - GRPC_SERVER=server:50051
    depends_on:
      - server
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: tm_react
    ports:
      - "3000:3000"
    depends_on:
      - gateway
    restart: unless-stopped