FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY thread_monitor.proto .

RUN python -m grpc_tools.protoc \
        -I. \
        --python_out=. \
        --grpc_python_out=. \
        thread_monitor.proto

COPY server.py .

EXPOSE 50051

CMD ["python", "-u", "server.py"]