"""
Servidor gRPC — Thread Monitor
Lee threads del sistema con psutil y los transmite por streaming.
"""
import grpc
import time
import psutil
from concurrent import futures

# These modules were generated by protoc, don't edit them
import thread_monitor_pb2
import thread_monitor_pb2_grpc


# We implement all the .protoc generated logic here
class ThreadMonitorServicer(thread_monitor_pb2_grpc.ThreadMonitorServicer):
    def _build_snapshot(self, pid: int = 0) -> thread_monitor_pb2.ThreadSnapshot:
        thread_list = []
        # Iterate through all processes (unless specified PID is provided)
        procs = (
            [psutil.Process(pid)] if pid
            else psutil.process_iter(['pid', 'name', 'status'])
        )
        for proc in procs:
            try:
                info = proc.info if hasattr(proc, 'info') else proc.as_dict(['pid', 'name', 'status'])
                for t in proc.threads():
                    thread_list.append(thread_monitor_pb2.ThreadInfo(
                        tid=t.id,
                        pid=info['pid'],
                        process_name=info['name'] or 'unknown',
                        status=info['status'] or 'unknown',
                        user_time=t.user_time,
                        system_time=t.system_time,
                    ))
            except (psutil.NoSuchProcess, psutil.AccessDenied, psutil.ZombieProcess):
                # The process can finish while we read it (just ignore this)
                pass
        # System global statistics
        mem = psutil.virtual_memory()
        stats = thread_monitor_pb2.SystemStats(
            cpu_percent=psutil.cpu_percent(interval=None),
            memory_used=mem.used,
            memory_total=mem.total,
        )
        return thread_monitor_pb2.ThreadSnapshot(
            timestamp_ms=int(time.time() * 1000),
            threads=thread_list,
            total_count=len(thread_list),
            stats=stats,
        )

    # RPC 1: unique snapshot
    def GetSnapshot(self, request, context):
        return self._build_snapshot(request.pid)

    # RPC 2: Continuos Streaming
    def StreamThreads(self, request, context):
        interval_sec = max(request.interval_ms, 100) / 1000.0
        while context.is_active():
            yield self._build_snapshot(request.pid)
            time.sleep(interval_sec)


def serve(port: int = 50051):
    # Thread pool to handle concurrent petitions
    server = grpc.server(futures.ThreadPoolExecutor(max_workers=10))

    # Register the inplementation
    thread_monitor_pb2_grpc.add_ThreadMonitorServicer_to_server(
        ThreadMonitorServicer(), server
    )

    # Listens on all interfacess (IPv4 + IPv6)
    server.add_insecure_port(f'[::]:{port}')
    server.start()
    print(f"[ThreadMonitor] Server listening on port {port}")
    print("[ThreadMonitor] Ctrl+C to stop")

    try:
        server.wait_for_termination()
    except KeyboardInterrupt:
        server.stop(grace=2)
        print("\n[ThreadMonitor] Server has been stopped!")


if __name__ == '__main__':
    serve()